# Generated by Django 3.1.2 on 2021-01-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fileSize',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
