# Generated by Django 3.1.2 on 2021-01-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0002_product_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
