# Generated by Django 3.1.2 on 2021-01-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0003_auto_20210115_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Upload/files'),
        ),
    ]
