# Generated by Django 3.1.2 on 2021-01-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0007_auto_20210116_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_request_id', models.CharField(max_length=200, unique=True)),
                ('payment_id', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Download.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Download.user')),
            ],
        ),
    ]
